### PR TITLE
Development

### PR DESCRIPTION
**Pull request by macnick**

### CODE REVIEW

**Comment by Torres-ssf** [comment]
### Congratulations team 👏. 
Your project looks really great. But it needs some changes to be in accord with Microverse guidelines. They are:

- [x] It's best practice to leave all the styles in a separate file. Please kindly put the styles from the HTML file inside your CSS file.

- [x] The NY Times logo must be a link(both logos).

- [x] The second NY Time logo must be inside the footer.

- [x] The project must have a descriptive README.md file.

- [x] Links in the footer should be organized using the `ul` tag and positioned with `display: flex` or *floats*

**Review by bellom — CHANGES_REQUESTED** [review]
Hi @macnick @dannyclever,
Great work so far guys, for some reason you didn't completely solved the issue from previous review.
From the last review you were told to do the following;
1.  The second NY Time logo must be inside the footer.
_hint:_ check out this [link](https://www.themelocation.com/best-html5-practices) on HTML tags structuring
2. The project must have a descriptive README.md file.
_hint:_ it great to have live version link to your project inside your README file, checkout this [video tutorial](https://www.loom.com/share/f7688bd6dbb54ae2a4e80a621fa7665d)

Kindly fix no 1&2 and submit another code review, :+1:  await you!

**Comment by macnick** [comment]
Hello @bellom,
Thank you for your review. 
1. The 2nd logo is in the footer now. 
2. We have a beautiful README.md file. Maybe you missed it? It is in development branch with screenshot and all. 
Also we have a link for the page which will start working as soon as we merge with the master. Hosting in github is only from master.

**Comment by Torres-ssf** [comment]
### Great work team 👏
You can merge to master now. Don't forget to submit the form. 👍

**Pull request merged**
